# Generated by Django 2.1.5 on 2019-01-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_year',
            new_name='work_years',
        ),
    ]
