# Generated by Django 2.1.5 on 2019-01-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='moblie',
            new_name='mobile',
        ),
    ]
